name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*'   # все теги вида v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create a release and upload assets
      
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.x'

      - name: Build & publish
        run: |
          dotnet publish -c Release -r win-x64 --self-contained false -o ./publish
          cd publish
          zip -r ../app-${{ github.ref_name }}.zip *
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }} # Uses the pushed tag name as the release tag
          name: Release ${{ github.ref_name }} # Sets the release name
          body: |
            ## Release Notes for ${{ github.ref_name }}
            
            This is an automated release created by GitHub Actions.
            
            ### Changes:
            - Add your release notes here.
          files: |
            ./app-${{ github.ref_name }}.zip
          draft: false # Set to true to create a draft release
          prerelease: false # Set to true for a prerelease
          generate_release_notes: true # Automatically generate release notes based on commits

